version: '3.8'

services:
  backend:
    image: exchange-rates
    build:
      context: ./exchange_rates
      dockerfile: Dockerfile
    container_name: exchange-rates-backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py default_currencies &&
             python manage.py get_exchange_rates &&
             python3 -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - data:/app/exchange-rates
      - ./exchange_rates:/app/exchange-rates
    env_file:
      - ./exchange_rates/.env
    deploy:
      resources:
        limits:
          memory: 512M 
        reservations:
          memory: 256M

volumes:
  data: